* Introduction

2018 basketball project

Use player trajectories to predict model player trajectories

# We use this [[https://docs.google.com/presentation/d/1UUQPWn69poKy3clSZHIpD6xedAG1rGOM1_9YFDfq0PU/edit#slide=id.g42b656bfa3_0_0][Google Slides]] to keep the notes

* Code Structure

We reuse the code genearted for 2017 basketball project for preprocessing the data.

We record the whole possession: where a possession is the time from the player
getting the ball until ball movement stops.

The data is contained on mld3 server: /data1/bball2017/traj_data ordered by
gamecode. To generate this data, we first run data_pipeline.py. Then use
check_data to obtain defect_possession.pkl (containing a list of defect
possessions). After removing those defect possessions using
rm_defect_possessions.py, we have 763,225 possessions for 3 years data
(2014-2017). Note that the data is already generated, don't try to generate it
again!

The entry point of running the code is main.py. use

#+BEGIN_SRC bash
python main.py -h
#+END_SRC

to see available command line options.

# The injury data scraper is contained in the scraper directory. Player names
# comes from the legacy directory and can be generated with
# legacy/get_player_names.py. This is deprecated, we no longer look at player
# injury data.

** legacy

Legacy code (eg. definition of possesion) is put into legacy folder

** lib

Contains useful code for current project

* Data 
  
  ../traj_data contains possession data for each game.  We chop each possession
  into 1s chunks. We either predict the possession outcome or next second
  frames. We later turn this information into pytorch dataset.
  
* Event Meaning

#+BEGIN_EXAMPLE
event-id="10" event-description="Substitution"
event-id="11" event-description="Timeout"
event-id="12" event-description="Jump Ball"
event-id="15" event-description="End Period"
#+END_EXAMPLE

For more search in NBA_FINALPBP_EXP\$2016020610.XML

* Design Choice

ignore pbp_seq_num: don't use play by play definition of possession to mark
previous event; Use my definition instead.
